### ISSUE TITLE
devcontainer docker build is broken due to old signing key

### ISSUE THREAD

**Issue by tommyp1ckles** [envoyproxy/envoy-build-tools#163]
*Title*: *devcontainer docker build is brokend due to old signing key*

*Description*:
`.devcontainer/Dockerfile` build seems to be broken due to an out of date signing key for apt.kitware. 

The current base image version contains the following one:
```
pub   rsa4096 2020-12-08 [SC] [expires: 2023-06-01]
      2EEA 8022 39DD F0E5 2942  A7B4 FCEE 74BB 7F3C 88C8
uid           [ unknown] Kitware Apt Archive Automatic Signing Key (2021) <debian@kitware.com>
sub   rsa4096 2020-12-08 [S] [expires: 2023-06-01]
```

However there seems to be a newer one available: `wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg`. Bumping the devcontainer build image to `514e2f7bc36c1f0495a523b16aab9168a4aa13b6` (which includes the 2022 kitware key) seems to fix the build for me.

*Repro steps*:
run `docker build .devcontainer` or try creating dev container in VSCode.

*Logs*:
```
W: GPG error: https://apt.kitware.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6AF7F09730B3F0A4
E: The repository 'https://apt.kitware.com/ubuntu bionic InRelease' is not signed.
```

**Comment by phlax** [comment]
thanks for reporting this @tommyp1ckles ive shifted it to this repo as the problem afaict is with the build image that is maintained here

**Comment by tommyp1ckles** [comment]
@phlax Sounds good. Seems like the newer builds on your docker hub pick up the new key. Might just be a case of bumping the docker image?

**Comment by phlax** [comment]
> Might just be a case of bumping the docker image?

@tommyp1ckles i think you are right - i moved here because i thought the image was up to date - but actually it hasnt been bumped since october 21, and there was a new image created in envoy 13 days ago

do you want to raise a PR to update the images in envoy ? 

the newer hash image is

envoyproxy/envoy-build-ubuntu:514e2f7bc36c1f0495a523b16aab9168a4aa13b6

an example of updating previously can be seen here

https://github.com/envoyproxy/envoy/commit/a29f9b789c7993b947750e5827de3fe9fbc10a47

lmk, im happy to do it it if necessary

**Comment by tommyp1ckles** [comment]
@phlax Ok, sounds good. I'll make a  PR.

**Comment by tommyp1ckles** [comment]
Created: https://github.com/envoyproxy/envoy/pull/19949

Should I bump the build tools repo version as well?
